### ISSUE TITLE
BUG: There is no hygienometr

### ISSUE THREAD

**Issue by JanPokorny** [norik16/psmf2017#2]
# Bug description
There is no hygienometr.

---

# Steps to reproduce
1. Open the website
2. Look for hygienometr

## Expected behavior
Hygienometr.

## Actual behavior
There is no hygienometr.

---

# Proposed fix
Add hygienometr.

**Comment by JanPokorny** [comment]
@norik16, you have failed me. *CRI*

**Comment by JanPokorny** [comment]
@ronaldluc still salty about this

**Comment by ronaldluc** [comment]
And you made me laugh 3 years later when it is needed the most.
